# This is a basic workflow to help you get started with Actions

name: build-deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is to build and deploy the repository
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: koenvdm/sdk6buildtools:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # run script that builds all examples
      - name: build script
        run: |
          .github/scripts/build-all-examples.sh

      # run script that checks the result
      - name: find failing script
        run: |
          .github/scripts/find-failing.sh